name: "Build Storybook"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Save branch metadata for Chromatic
        run: |
          mkdir METADATA
          echo $BRANCH_NAME > ./METADATA/branch-name
          echo $DRAFT > ./METADATA/draft
        env:
          DRAFT: ${{ github.event.pull_request.draft }}
          BRANCH_NAME: ${{ github.event.pull_request.head.repo.fork && github.event.pull_request.head.label || github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: ./METADATA
          retention-days: 1
