name: "Chromatic"

on:
  workflow_run:
    workflows: ["Build Storybook"]
    types:
      - completed

jobs:
  chromatic-deployment:
    if: github.event.pull_request.draft == false
    # Operating System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.workflow_run.pull_requests[0].number }}/merge
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: "Download build artifact"
        uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: ./storybook-static
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
