name: "Chromatic"

on:
  workflow_run:
    workflows: ["Build Storybook"]
    types:
      - completed

jobs:
  chromatic-deployment:
    if: github.event.pull_request.draft == false
    # Operating System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get branch for Chromatic
        uses: actions/github-script@v7
        id: chromatic_branch
        with:
          script: |
            const { data:pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.workflow_run.pull_requests[0].number }}
            });

            const label = pr.head.repo.fork ? pr.head.label : pr.head.ref;

            console.log(label);
